<a href="https://colab.research.google.com/github/IbHansen/wb-debt-simulation/blob/main/simulation/Specification_debt_simulation_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#This is code to manage dependencies if the notebook is executed in the google colab cloud service
if 'google.colab' in str(get_ipython()):
  import os
  os.system('apt -qqq install graphviz')
  os.system('pip -qqq install ModelFlowIb')

In [9]:
import pandas as pd
import re

from modelclass import model

In [10]:
# just a helper for colab reference 

from modelhelp import colab_link
colab_link('Specification_debt_simulation_model',badge=True,render=0)

<a href="https://colab.research.google.com/github/IbHansen/wb-debt-simulation/blob/main/simulation/Specification_debt_simulation_model.ipynb" target="_blank"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
mhist,basehist = model.modelload('model/hist',run=1,silent=1
                                )
mport,baseport = model.modelload('model/port',run=1,silent=1 )

Zipped file read:  model\hist.pcim
Zipped file read:  model\port.pcim

In [12]:
mdebt=mhist+mport

In [13]:
base = pd.concat([baseport,basehist],axis=1)
base

,CURRENT_YEAR,BOND_SHARE_DOM,NEW_ISSUE_SHARE__1_YEAR_DOM,NEW_ISSUE_SHARE__5_YEAR_DOM,NEW_ISSUE_SHARE__10_YEAR_DOM,INTEREST_RATE__DOM__1,INTEREST_RATE__DOM__5,INTEREST_RATE__DOM__10,INTEREST_RATE_USD__1,INTEREST_RATE_USD__5,...,AMORTIZING_IN_CURRENCY__10_HIST_USD,AMORTIZING_IN_CURRENCY__10_HIST_DOM,STOCK_ULTIMO__10_HIST_USD,STOCK_PRIMO_IN_CURRENCY__10_HIST_USD,AMORTIZING__10_HIST_DOM,INTEREST_PAYMENTS__10_HIST_USD,STOCK_PRIMO__HIST,AMORTIZING_SHARE_PR_TIME__10_HIST_DOM,STOCK_PRIMO__10_HIST_DOM,STOCK_PRIMO_IN_CURRENCY__10_HIST_DOM
2025,2025.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2026,2026.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,2.0,100.0,180.0,20.0,100.0,4.0,1200.0,0.1,1000.0,1000.0
2027,2027.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,2.0,100.0,160.0,18.0,100.0,3.6,1080.0,0.1,900.0,900.0
2028,2028.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,2.0,100.0,140.0,16.0,100.0,3.2,960.0,0.1,800.0,800.0
2029,2029.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,2.0,100.0,120.0,14.0,100.0,2.8,840.0,0.1,700.0,700.0
2030,2030.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,2.0,100.0,100.0,12.0,100.0,2.4,720.0,0.1,600.0,600.0
2031,2031.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,2.0,100.0,80.0,10.0,100.0,2.0,600.0,0.1,500.0,500.0
2032,2032.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,2.0,100.0,60.0,8.0,100.0,1.6,480.0,0.1,400.0,400.0
2033,2033.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,2.0,100.0,40.0,6.0,100.0,1.2,360.0,0.1,300.0,300.0
2034,2034.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,2.0,100.0,20.0,4.0,100.0,0.8,240.0,0.1,200.0,200.0
2035,2035.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,2.0,100.0,0.0,2.0,100.0,0.4,120.0,0.1,100.0,100.0
2036,2036.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2037,2037.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2038,2038.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2039,2039.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2040,2040.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2041,2041.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2042,2042.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2043,2043.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2044,2044.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2045,2045.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2046,2046.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2047,2047.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2048,2048.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2049,2049.0,100.0,0.0,100.0,0.0,1.0,1.0,1.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
_ = mdebt(base,2026,2049)

In [20]:
mdebt['stock_primo*_hist_*'].df

,STOCK_PRIMO_IN_CURRENCY__10_HIST_DOM,STOCK_PRIMO_IN_CURRENCY__10_HIST_USD,STOCK_PRIMO__10_HIST_DOM,STOCK_PRIMO__10_HIST_USD
2026,1000.0,20.0,1000.0,200.0
2027,900.0,18.0,900.0,180.0
2028,800.0,16.0,800.0,160.0
2029,700.0,14.0,700.0,140.0
2030,600.0,12.0,600.0,120.0
2031,500.0,10.0,500.0,100.0
2032,400.0,8.0,400.0,80.0
2033,300.0,6.0,300.0,60.0
2034,200.0,4.0,200.0,40.0
2035,100.0,2.0,100.0,20.0
2036,0.0,0.0,0.0,0.0
2037,0.0,0.0,0.0,0.0
2038,0.0,0.0,0.0,0.0
2039,0.0,0.0,0.0,0.0
2040,0.0,0.0,0.0,0.0
2041,0.0,0.0,0.0,0.0
2042,0.0,0.0,0.0,0.0
2043,0.0,0.0,0.0,0.0
2044,0.0,0.0,0.0,0.0
2045,0.0,0.0,0.0,0.0
2046,0.0,0.0,0.0,0.0
2047,0.0,0.0,0.0,0.0
2048,0.0,0.0,0.0,0.0
2049,0.0,0.0,0.0,0.0